# Generated by Django 4.2.23 on 2025-08-08 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalcredential',
            name='additional_credential_type',
            field=models.CharField(blank=True, choices=[('Membership', 'Membership'), ('License', 'License'), ('Certificate', 'Certificate'), ('Degree/Diploma', 'Degree/Diploma')], default='', max_length=16),
        ),
    ]
