# Generated by Django 4.2.23 on 2025-07-22 17:07

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_subscriptiontype_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptiontype',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
