# Generated by Django 4.2.23 on 2025-07-22 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_subscriptiontype_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='interval',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('annual', 'Annual')], default='monthly', max_length=10),
        ),
    ]
