# Generated by Django 4.2.23 on 2025-08-09 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_zipcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='LookupMaintenance',
            fields=[
            ],
            options={
                'verbose_name': 'Lookup Maintenance',
                'verbose_name_plural': 'Lookup Maintenance',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.licensetype',),
        ),
    ]
