# Generated by Django 4.2.23 on 2025-07-22 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_subscription_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='stripe_payment_method_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
