# Generated by Django 4.2.23 on 2025-07-22 22:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0006_subscription_stripe_customer_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TherapistProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=128)),
                ('credentials', models.CharField(max_length=128)),
                ('display_name', models.CharField(blank=True, max_length=128)),
                ('tagline', models.CharField(blank=True, max_length=256)),
                ('short_bio', models.TextField()),
                ('license_number', models.CharField(max_length=64)),
                ('license_type', models.CharField(max_length=64)),
                ('issuing_state_board', models.CharField(max_length=64)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('license_verified', models.BooleanField(default=False)),
                ('license_upload', models.FileField(blank=True, null=True, upload_to='licenses/')),
                ('primary_office_address', models.CharField(max_length=256)),
                ('additional_locations', models.TextField(blank=True)),
                ('phone_number', models.CharField(max_length=32)),
                ('email_address', models.EmailField(max_length=254)),
                ('website_url', models.URLField(blank=True)),
                ('contact_form_toggle', models.BooleanField(default=True)),
                ('in_person_sessions', models.BooleanField(default=True)),
                ('telehealth', models.BooleanField(default=True)),
                ('telehealth_platforms', models.CharField(blank=True, max_length=128)),
                ('office_hours', models.CharField(blank=True, max_length=128)),
                ('external_scheduling_link', models.URLField(blank=True)),
                ('secure_document_upload', models.BooleanField(default=False)),
                ('cities_counties', models.CharField(blank=True, max_length=256)),
                ('zip_codes', models.CharField(blank=True, max_length=128)),
                ('practice_areas_tags', models.CharField(max_length=256)),
                ('treatment_approaches', models.CharField(blank=True, max_length=256)),
                ('client_populations', models.CharField(blank=True, max_length=256)),
                ('languages_spoken', models.CharField(blank=True, max_length=128)),
                ('trauma_informed_training', models.BooleanField(default=False)),
                ('neurodiversity_training', models.BooleanField(default=False)),
                ('profile_photo', models.ImageField(upload_to='profile_photos/')),
                ('intro_video_url', models.URLField(blank=True)),
                ('practice_logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('certificate_logos', models.ImageField(blank=True, null=True, upload_to='certificates/')),
                ('degrees_institutions', models.CharField(blank=True, max_length=256)),
                ('graduation_years', models.CharField(blank=True, max_length=32)),
                ('professional_associations', models.CharField(blank=True, max_length=256)),
                ('continuing_ed_certifications', models.CharField(blank=True, max_length=256)),
                ('session_fee_package_rates', models.CharField(max_length=128)),
                ('insurances_accepted', models.CharField(blank=True, max_length=256)),
                ('sliding_scale_scholarship', models.BooleanField(default=False)),
                ('sliding_scale_description', models.CharField(blank=True, max_length=256)),
                ('free_consultation_offer', models.BooleanField(default=False)),
                ('cancellation_policy', models.TextField(blank=True)),
                ('wheelchair_access', models.BooleanField(default=False)),
                ('wheelchair_access_description', models.CharField(blank=True, max_length=256)),
                ('multilingual_materials', models.CharField(blank=True, max_length=128)),
                ('client_portal_demo_link', models.URLField(blank=True)),
                ('digital_homework_worksheets', models.FileField(blank=True, null=True, upload_to='homework/')),
                ('publications_books_podcasts', models.CharField(blank=True, max_length=256)),
                ('workshops_group_programs', models.CharField(blank=True, max_length=256)),
                ('pro_bono_community_outreach', models.BooleanField(default=False)),
                ('pro_bono_description', models.CharField(blank=True, max_length=256)),
                ('memberships_awards', models.CharField(blank=True, max_length=256)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
