# Generated by Django 4.2.23 on 2025-07-22 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_therapistprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityCounty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientPopulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LicenseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MultilingualMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PracticeAreaTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StateBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TelehealthPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TreatmentApproach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ZipCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='therapistprofile',
            name='cities_counties',
        ),
        migrations.RemoveField(
            model_name='therapistprofile',
            name='client_populations',
        ),
        migrations.RemoveField(
            model_name='therapistprofile',
            name='insurances_accepted',
        ),
        migrations.RemoveField(
            model_name='therapistprofile',
            name='languages_spoken',
        ),
        migrations.RemoveField(
            model_name='therapistprofile',
            name='multilingual_materials',
        ),
        migrations.RemoveField(
            model_name='therapistprofile',
            name='practice_areas_tags',
        ),
        migrations.RemoveField(
            model_name='therapistprofile',
            name='professional_associations',
        ),
        migrations.RemoveField(
            model_name='therapistprofile',
            name='telehealth_platforms',
        ),
        migrations.RemoveField(
            model_name='therapistprofile',
            name='treatment_approaches',
        ),
        migrations.RemoveField(
            model_name='therapistprofile',
            name='zip_codes',
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='cities_counties',
            field=models.ManyToManyField(blank=True, to='users.citycounty'),
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='client_populations',
            field=models.ManyToManyField(blank=True, to='users.clientpopulation'),
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='insurances_accepted',
            field=models.ManyToManyField(blank=True, to='users.insurance'),
        ),
        migrations.AlterField(
            model_name='therapistprofile',
            name='issuing_state_board',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.stateboard'),
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='languages_spoken',
            field=models.ManyToManyField(blank=True, to='users.language'),
        ),
        migrations.AlterField(
            model_name='therapistprofile',
            name='license_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.licensetype'),
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='multilingual_materials',
            field=models.ManyToManyField(blank=True, to='users.multilingualmaterial'),
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='practice_areas_tags',
            field=models.ManyToManyField(to='users.practiceareatag'),
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='professional_associations',
            field=models.ManyToManyField(blank=True, to='users.professionalassociation'),
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='telehealth_platforms',
            field=models.ManyToManyField(blank=True, to='users.telehealthplatform'),
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='treatment_approaches',
            field=models.ManyToManyField(blank=True, to='users.treatmentapproach'),
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='zip_codes',
            field=models.ManyToManyField(blank=True, to='users.zipcode'),
        ),
    ]
