# Generated by Django 4.2.23 on 2025-08-10 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_therapistprofile_profile_photo_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='image_meta',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='image_meta',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
