# Generated by Django 4.2.23 on 2025-08-10 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_blogpost_image_meta_galleryimage_image_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='Marks the primary gallery image for emphasized display'),
        ),
    ]
