# Generated by Django 4.2.23 on 2025-07-23 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_therapistprofile_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapistprofile',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='therapistprofile',
            name='issue_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
