# Generated by Django 4.2.23 on 2025-07-24 12:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_therapistprofile_expiry_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='therapistprofile',
            name='zip_codes',
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Enter a valid 5-digit US ZIP code.', regex='^\\d{5}$')]),
        ),
    ]
