# Generated by Django 4.2.23 on 2025-07-24 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_therapistprofile_zip_codes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='licensetype',
            name='description',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='credential_description',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
