# Generated by Django 4.2.23 on 2025-07-24 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_licensetype_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapistprofile',
            name='city',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='state',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
