# Generated by Django 4.2.23 on 2025-08-11 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_split_intro_and_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapistprofile',
            name='intro_note',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='personal_statement_01',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='officehour',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
