# Generated by Django 4.2.23 on 2025-08-12 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_therapistprofile_intro_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapistprofile',
            name='no_show_policy',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
