# Generated by Django 4.2.23 on 2025-07-27 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_add_profile_stats'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedTherapistHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('cycle', models.PositiveIntegerField(default=1)),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.therapistprofile')),
            ],
        ),
        migrations.CreateModel(
            name='FeaturedBlogPostHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('cycle', models.PositiveIntegerField(default=1)),
                ('blog_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.blogpost')),
            ],
        ),
    ]
