# Generated by Django 4.2.23 on 2025-08-12
from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ('users', '0016_therapistprofile_no_show_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapistprofile',
            name='year_started_practice',
            field=models.CharField(max_length=4, blank=True),
        ),
    ]
