# Generated by Django 4.2.23 on 2025-08-12
from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ('users','0017_therapistprofile_year_started_practice'),
    ]
    operations = [
        migrations.AddField(
            model_name='therapistprofile',
            name='license_first_name',
            field=models.CharField(max_length=64, blank=True),
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='license_last_name',
            field=models.CharField(max_length=64, blank=True),
        ),
    ]
