# Generated by Django 4.2.23 on 2025-08-13 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_officehour'),
        ('users', '0018_licensed_name_fields'),
    ]

    operations = [
    ]
