# Generated by Django 4.2.23 on 2025-08-15 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_relax_license_number_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapistprofile',
            name='last_viewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
