# Generated by Django 4.2.23 on 2025-08-15 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_feedpost_rich_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedreaction',
            name='reaction',
            field=models.CharField(choices=[('like', 'Like'), ('celebrate', 'Celebrate'), ('support', 'Support'), ('insightful', 'Insightful'), ('love', 'Love'), ('laugh', 'Laugh')], max_length=16),
        ),
    ]
