# Generated by Django 4.2.23 on 2025-08-16 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_alter_feedreaction_reaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedpost',
            name='repost_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reposts', to='users.feedpost'),
        ),
    ]
