# Generated by Django 4.2.23 on 2025-08-18 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_feedpost_repost_of'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='blog_media/%Y/%m/')),
                ('type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=10)),
                ('meta', models.JSONField(blank=True, default=dict, null=True)),
                ('position', models.PositiveIntegerField(default=0, help_text='Ordering of media within the post')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='users.blogpost')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
    ]
