# Generated by Django 4.2.23 on 2025-08-19 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_blogmedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('category', models.CharField(blank=True, db_index=True, max_length=48)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='offers_testing',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='TestingTypeSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testing_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.testingtype')),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testing_types', to='users.therapistprofile')),
            ],
        ),
    ]
