# Generated by Django on 2025-08-19
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_testingtype_therapistprofile_offers_testing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapistprofile',
            name='online_scheduling_url',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='show_online_scheduling',
            field=models.BooleanField(default=False),
        ),
    ]
