# Mapping from JSON field names to TherapistProfile model field names
FIELD_MAP = {
    "First Name": "first_name",
    "Last Name": "last_name",
    "Credentials": "credentials",
    "Display Name": "display_name",
    "Tagline / Quote": "tagline",
    "Short Bio": "short_bio",
    "License Number": "license_number",
    "License Type": "license_type",
    "Issuing State/Board": "issuing_state_board",
    "Issue / Expiry Dates": ["issue_date", "expiry_date"],
    "Verify via API": "license_verified",
    "License Upload (alt)": "license_upload",
    "Primary Office Address": "primary_office_address",
    "Additional Locations": "additional_locations",
    "Phone Number": "phone_number",
    "Email Address": "email_address",
    "Website URL": "website_url",
    "Contact Form Toggle": "contact_form_toggle",
    "In-Person Sessions": "in_person_sessions",
    "Telehealth (Video/Phone)": "telehealth",
    "Telehealth Platforms": "telehealth_platforms",
    "Office Hours / Schedule": "office_hours",
    "External Scheduling Link": "external_scheduling_link",
    "Secure Document Upload": "secure_document_upload",
    "Cities / Counties": "cities_counties",
    "ZIP Codes": "zip_codes",
    "Practice Areas / Tags": "practice_areas_tags",
    "Treatment Approaches": "treatment_approaches",
    "Client Populations": "client_populations",
    "Languages Spoken": "languages_spoken",
    "Trauma-Informed Training": "trauma_informed_training",
    "Neurodiversity Training": "neurodiversity_training",
    "Profile Photo": "profile_photo",
    "Intro Video URL / Upload": "intro_video_url",
    "Practice Logo / Colors": "practice_logo",
    "Certificate Logos": "certificate_logos",
    "Degrees & Institutions": "degrees_institutions",
    "Graduation Year(s)": "graduation_years",
    "Professional Associations": "professional_associations",
    "Continuing Ed / Certifications": "continuing_ed_certifications",
    "Session Fee / Package Rates": "session_fee_package_rates",
    "Insurances Accepted": "insurances_accepted",
    "Sliding Scale / Scholarship": ["sliding_scale_scholarship", "sliding_scale_description"],
    "Free 15-Min Consultation Offer": "free_consultation_offer",
    "Cancellation / No-Show Policy": "cancellation_policy",
    "Wheelchair Access / ADA Features": ["wheelchair_access", "wheelchair_access_description"],
    "Multilingual Materials Offered": "multilingual_materials",
    "Client Portal Demo Link": "client_portal_demo_link",
    "Digital Homework & Worksheets": "digital_homework_worksheets",
    "Publications, Books & Podcasts": "publications_books_podcasts",
    "Workshops & Group Programs": "workshops_group_programs",
    "Pro Bono / Community Outreach": ["pro_bono_community_outreach", "pro_bono_description"],
    "Memberships & Awards": "memberships_awards",
}
