# Mapping from JSON field names to TherapistProfile model field names
FIELD_MAP = {
    "First Name": "first_name",
    "Middle Name": "middle_name",
    "Last Name": "last_name",
    "Title": "title",
    "Display Title": "display_title",
    "Personal Statement Q1": "personal_statement_q1",
    "Personal Statement Q2": "personal_statement_q2",
    "Personal Statement Q3": "personal_statement_q3",
    "Practice Name": "practice_name",
    "Phone Number": "phone_number",
    "Phone Extension": "phone_extension",
    "Receive Calls From Client": "receive_calls_from_client",
    "Mobile Number": "mobile_number",
    "Receive Texts From Clients": "receive_texts_from_clients",
    "Office Email": "office_email",
    "Receive Emails From Clients": "receive_emails_from_clients",
    "Receive Emails When Client Calls": "receive_emails_when_client_calls",
    "Intro Statement": "intro_statement",
    "Therapy Delivery Method": "therapy_delivery_method",
    "Accepting New Clients": "accepting_new_clients",
    "Offers Intro Call": "offers_intro_call",
    "Individual Session Cost": "individual_session_cost",
    "Couples Session Cost": "couples_session_cost",
    "Sliding Scale Pricing Available": "sliding_scale_pricing_available",
    "Finance Note": "finance_note",
    "Credentials Note": "credentials_note",
    "Profile Photo": "profile_photo",
    "Practice Website URL": "practice_website_url",
    "Facebook URL": "facebook_url",
    "Instagram URL": "instagram_url",
    "LinkedIn URL": "linkedin_url",
    "Twitter URL": "twitter_url",
    "TikTok URL": "tiktok_url",
    "YouTube URL": "youtube_url",
    "Therapy Types Note": "therapy_types_note",
    "Specialties Note": "specialties_note",
    "Mental Health Role": "mental_health_role",
    "License Number": "license_number",
    "License Expiration": "license_expiration",
    # "Credential Type": "credential_type", (removed)
    "License State": "license_state",
    "Date Of Birth": "date_of_birth",
    "Gender": "gender",
}
